services:
  worker:
    container_name: heroku_ub
    build:
      context: .
    stdin_open: true
    tty: true
    init: true
    volumes:
      - worker:/data
    stop_signal: SIGINT
    restart: unless-stopped
    ports:
      - "${EXTERNAL_PORT:-8088}:8088"

volumes:
  worker:
